#!/bin/bash
source ./functions.sh

# check os
os=$(check_os)
# if os is unknown then exit
if [[ $os == "Unknown" ]]; then
    echo "Unknown OS. Exiting."
    exit 1
fi

echo "$os Detected. Checking package manager..."

# check package manager
if ! check_package_man; then
  # Install package manager
  install_package_manager
  # if package manager is null after install then exit
  if ! check_package_man; then
    echo "No package manager detected. Exiting."
    exit 1
  fi
fi

pkg=$(check_package_man)

echo "Detected $pkg, using as package manager for installation."
# this is where the script will install the packages

# Install OS Specific Tools and Apps First
if [[ "$os" == "MacOS" ]]; then
  # Install Xcode Cli
  read -p "Do you want to install xcode command line tools? [Y/n] " answer
  if answer_default_y "$answer"; then
    echo "After installing the command line tools, please install xcode from the app store."
    xcode-select --install
  fi

  read -p "Do you want to add fonts to homebrew? [Y/n] " answer
  if answer_default_y "$answer"; then
    brew tap homebrew/cask-fonts
  fi

  read -p "Do you want to install rectangle? [Y/n] " answer
  if answer_default_y "$answer"; then
    brew install rectangle
  fi
fi

# Install shell
read -p "Do you want to install an additional shell? [Y/n] " answer
if answer_default_y "$answer"; then
    read -p "Do you want to install the fish shell? [Y/n] " answer
    if answer_default_y "$answer"; then
        echo "Installing fish..."
        pkg_man_install fish
    fi

    read -p "Do you want to install the zsh shell? [Y/n] " answer
    if answer_default_y "$answer"; then
        echo "Installing zsh..."
        pkg_man_install zsh
    fi
fi

# Install Cross Platform Apps Last

echo "Installation complete."